spring.application.name=tareas-app

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.h2.console.enabled=false
app.h2-console.enabled=false

logging.level.com.tareas.app=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}