# Nombre de como se va a llamar la app desde este proyecto de intellij
spring.application.name=tareas-app

# Configuración de H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración de la consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
app.cors.allowed-origin=http://localhost:4200
app.h2-console.enabled=true

# ===============================
# Configuración de Logs
# ===============================
logging.level.com.tareas.app=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR

# Guardar logs en archivo
logging.file.name=logs/tareas-app.log
logging.file.path=logs

# Formato de los logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Rotación de archivos (opcional)
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.max-file-size=10MB

# ===============================
# Configuración JWT
# ===============================

# Clave codeada en Base64 para firmar los tokens (Base64)
jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUV2l0aEFkZWN1YXRlTGVuZ3RoMTIzNDU2

# Tiempo de expiración del token (milisegundos)
# 86400000 = 24 horas
jwt.expiration=86400000