spring.config.import=classpath:application-runtime.properties
spring.application.name=tareas-app-local
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}
jwt.issuer=${JWT_ISSUER:http://localhost:8080}
jwt.audience=${JWT_AUDIENCE:tareas-app-local}
jwt.admin.issuer=${JWT_ADMIN_ISSUER:http://localhost:8080}
jwt.admin.audience=${JWT_ADMIN_AUDIENCE:donit-admin-local}
springdoc.api-docs.enabled=${SWAGGER_ENABLED:true}
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:true}
