-- =============================================================================
-- V2__refresh_tokens.sql
--
-- Tabla de refresh tokens para el sistema de sesiones.
--   - Nunca almacena el refresh token en claro: solo token_hash (SHA-256 hex).
--   - token_hash UNIQUE para localizar el token por hash (lookup directo).
--   - FK hacia usuarios, igual que el resto de FKs del proyecto (sin cascade).
--   - Indices para busqueda por usuario y limpieza por expiracion.
--
-- Reglas del proyecto:
--   - V2 es inmutable una vez publicada (Flyway comprueba checksum).
--   - Se aplica SOLO sobre un schema con V1 ya aplicada (o baseline v1).
--   - Sin datos, sin DROP ni ALTER destructivo.
-- =============================================================================

CREATE TABLE refresh_tokens (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  bigint      NOT NULL,
    token_hash  varchar(64) NOT NULL,
    created_at  timestamp   NOT NULL DEFAULT now(),
    expires_at  timestamp   NOT NULL,
    revoked_at  timestamp,
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX idx_refresh_tokens_usuario_id ON refresh_tokens (usuario_id);
CREATE INDEX idx_refresh_tokens_expires_at  ON refresh_tokens (expires_at);