-- =============================================================================
-- V3__admin_auth.sql
--
-- Tablas de autenticacion administrativa para el panel Donit Admin.
--   - Completamente separada de usuarios Android (tablas usuarios, refresh_tokens).
--   - admin_users: credenciales de administradores del panel.
--   - admin_refresh_tokens: tokens de sesion administrativa (solo SHA-256 hash).
--
-- Reglas del proyecto:
--   - V3 es inmutable una vez publicada (Flyway comprueba checksum).
--   - Se aplica SOLO sobre un schema con V1+V2 ya aplicadas.
--   - Sin datos, sin DROP ni ALTER destructivo.
-- =============================================================================

-- =============================================================================
-- Tabla de administradores del panel
-- =============================================================================
CREATE TABLE admin_users (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      varchar(50)  NOT NULL,
    email         varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    enabled       boolean      NOT NULL DEFAULT true,
    created_at    timestamp    NOT NULL DEFAULT now(),
    last_login    timestamp,
    CONSTRAINT uk_admin_users_username UNIQUE (username),
    CONSTRAINT uk_admin_users_email    UNIQUE (email)
);

-- =============================================================================
-- Refresh tokens de administradores
-- =============================================================================
CREATE TABLE admin_refresh_tokens (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id   bigint      NOT NULL,
    token_hash      varchar(64) NOT NULL,
    created_at      timestamp   NOT NULL DEFAULT now(),
    expires_at      timestamp   NOT NULL,
    revoked_at      timestamp,
    CONSTRAINT uk_admin_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_admin_refresh_tokens_user
        FOREIGN KEY (admin_user_id) REFERENCES admin_users (id)
);

CREATE INDEX idx_admin_refresh_tokens_user    ON admin_refresh_tokens (admin_user_id);
CREATE INDEX idx_admin_refresh_tokens_expires ON admin_refresh_tokens (expires_at);
