-- Expand-only: the previous image ignores these tables on rollback.
ALTER TABLE usuarios ADD COLUMN protected_from_admin_mutation boolean NOT NULL DEFAULT false;

CREATE TABLE admin_permissions (
    admin_user_id bigint NOT NULL REFERENCES admin_users(id),
    permission varchar(32) NOT NULL,
    PRIMARY KEY (admin_user_id, permission),
    CONSTRAINT ck_admin_permission CHECK (permission IN ('ADMIN_READ', 'USER_WRITE', 'USER_DELETE', 'TASK_WRITE'))
);

-- Legacy administrators already had unrestricted access. Snapshot that access once.
INSERT INTO admin_permissions (admin_user_id, permission)
SELECT id, permission
FROM admin_users CROSS JOIN (VALUES ('ADMIN_READ'), ('USER_WRITE'), ('USER_DELETE'), ('TASK_WRITE')) AS p(permission);

CREATE TABLE admin_audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id bigint,
    operation varchar(64) NOT NULL,
    resource_type varchar(32) NOT NULL,
    resource_id bigint,
    outcome varchar(16) NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    correlation_id varchar(100)
);
CREATE INDEX idx_admin_audit_events_actor_time ON admin_audit_events(admin_user_id, occurred_at);
