-- Expand-only. The bridge image ignores the new tables and understands DEMO permissions.
ALTER TABLE admin_permissions DROP CONSTRAINT ck_admin_permission;
ALTER TABLE admin_permissions ADD CONSTRAINT ck_admin_permission CHECK (permission IN (
    'ADMIN_READ', 'USER_WRITE', 'USER_DELETE', 'TASK_WRITE',
    'DEMO_READ', 'DEMO_WRITE', 'DEMO_PUBLISH', 'DEMO_RESTORE'
));

CREATE TABLE demo_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    handle varchar(40) NOT NULL,
    display_name varchar(100) NOT NULL,
    bio varchar(500),
    publication_status varchar(16) NOT NULL DEFAULT 'DRAFT',
    fixture_key varchar(80),
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    published_at timestamp with time zone,
    CONSTRAINT uk_demo_users_public_id UNIQUE (public_id),
    CONSTRAINT uk_demo_users_handle UNIQUE (handle),
    CONSTRAINT uk_demo_users_fixture_key UNIQUE (fixture_key),
    CONSTRAINT ck_demo_users_handle CHECK (handle ~ '^[a-z0-9][a-z0-9_-]{2,39}$'),
    CONSTRAINT ck_demo_users_display_name CHECK (length(btrim(display_name)) > 0),
    CONSTRAINT ck_demo_users_status CHECK (publication_status IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT ck_demo_users_published_at CHECK (publication_status <> 'PUBLISHED' OR published_at IS NOT NULL),
    CONSTRAINT ck_demo_users_version CHECK (version >= 0)
);
CREATE INDEX idx_demo_users_status_handle ON demo_users (publication_status, handle);

CREATE TABLE demo_task_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    demo_user_id bigint NOT NULL,
    name varchar(50) NOT NULL,
    description varchar(500),
    color varchar(7) NOT NULL,
    publication_status varchar(16) NOT NULL DEFAULT 'DRAFT',
    fixture_key varchar(80),
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    published_at timestamp with time zone,
    CONSTRAINT uk_demo_task_types_public_id UNIQUE (public_id),
    CONSTRAINT uk_demo_task_types_fixture_key UNIQUE (fixture_key),
    CONSTRAINT uk_demo_task_types_id_user UNIQUE (id, demo_user_id),
    CONSTRAINT fk_demo_task_types_user FOREIGN KEY (demo_user_id) REFERENCES demo_users (id),
    CONSTRAINT ck_demo_task_types_name CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_demo_task_types_color CHECK (color ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT ck_demo_task_types_status CHECK (publication_status IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT ck_demo_task_types_published_at CHECK (publication_status <> 'PUBLISHED' OR published_at IS NOT NULL),
    CONSTRAINT ck_demo_task_types_version CHECK (version >= 0)
);
CREATE INDEX idx_demo_task_types_user_status_name ON demo_task_types (demo_user_id, publication_status, name);

CREATE TABLE demo_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    demo_user_id bigint NOT NULL,
    demo_task_type_id bigint NOT NULL,
    title varchar(255) NOT NULL,
    description varchar(500),
    due_date date NOT NULL,
    completed boolean NOT NULL DEFAULT false,
    urgency integer NOT NULL DEFAULT 0,
    publication_status varchar(16) NOT NULL DEFAULT 'DRAFT',
    fixture_key varchar(80),
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    published_at timestamp with time zone,
    CONSTRAINT uk_demo_tasks_public_id UNIQUE (public_id),
    CONSTRAINT uk_demo_tasks_fixture_key UNIQUE (fixture_key),
    CONSTRAINT fk_demo_tasks_user FOREIGN KEY (demo_user_id) REFERENCES demo_users (id),
    CONSTRAINT fk_demo_tasks_type_owner FOREIGN KEY (demo_task_type_id, demo_user_id)
        REFERENCES demo_task_types (id, demo_user_id),
    CONSTRAINT ck_demo_tasks_title CHECK (length(btrim(title)) > 0),
    CONSTRAINT ck_demo_tasks_urgency CHECK (urgency BETWEEN 0 AND 2),
    CONSTRAINT ck_demo_tasks_status CHECK (publication_status IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT ck_demo_tasks_published_at CHECK (publication_status <> 'PUBLISHED' OR published_at IS NOT NULL),
    CONSTRAINT ck_demo_tasks_version CHECK (version >= 0)
);
CREATE INDEX idx_demo_tasks_user_status_due ON demo_tasks (demo_user_id, publication_status, due_date, id);
CREATE INDEX idx_demo_tasks_type_owner ON demo_tasks (demo_task_type_id, demo_user_id);

-- Empty singleton until a later catalog operation explicitly initializes it.
CREATE TABLE demo_catalog_control (
    id smallint PRIMARY KEY,
    revision bigint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ck_demo_catalog_control_singleton CHECK (id = 1),
    CONSTRAINT ck_demo_catalog_control_revision CHECK (revision >= 0)
);
